research_task:
  description: >
    Conduct a thorough research on {stock_symbol}. Your analysis should include:
     1. Current stock price and historical performance (5 years).
     2. Key financial metrics (P/E, EPS growth, revenue growth, margins).
     3. Recent news and press releases (1 month).
     4. Analyst ratings and price targets (min 3 analysts).
     5. Reddit sentiment analysis (100 posts).
     6. Major institutional holders and recent changes.
     7. Competitive landscape and {stock_symbol}'s market share.
     Use reputable financial websites for data.
  
  expected_output: >
    A detailed 200-word research report with data sources and brief analysis.
  

technical_analysis_task:
  description: >
    Perform technical analysis on {stock_symbol}. Include:
       1. 50-day and 200-day moving averages (1 year).
       2. Key support and resistance levels (3 each).
       3. RSI and MACD indicators.
       4. Volume analysis (3 months).
       5. Significant chart patterns (6 months).
       6. Fibonacci retracement levels.
       7. Comparison with sector's average.
      Use the yf_tech_analysis tool for data.
  
  expected_output: >
    A 100-word technical analysis report with buy/sell/hold signals and annotated charts.
  

fundamental_analysis_task:
  description: >
    Conduct fundamental analysis of {stock_symbol}. Include:
      1. Review last 3 years of financial statements.
      2. Key ratios (P/E, P/B, P/S, PEG, Debt-to-Equity, etc.).
      3. Comparison with main competitors and industry averages.
      4. Revenue and earnings growth trends.
      5. Management effectiveness (ROE, capital allocation).
      6. Competitive advantages and market position.
      7. Growth catalysts and risks (2-3 years).
      8. DCF valuation model with assumptions.
      Use yf_fundamental_analysis tool for data.
  
  expected_output: >
     A 100-word fundamental analysis report with buy/hold/sell recommendation and key metrics summary.
  

report_task:
  description: >
    Create an investment report on {stock_symbol}. Include:
      1. Executive Summary: Investment recommendation.
      2. Company Snapshot: Key facts.
      3. Financial Highlights: Top metrics and peer comparison.
      4. Technical Analysis: Key findings.
      5. Fundamental Analysis: Top strengths and concerns.
      6. Risk and Opportunity: Major risk and growth catalyst.
      7. Reddit Sentiment: Key takeaway from sentiment analysis, including the number of positive, negative and neutral comments and total comments.
      8. Investment Thesis: Bull and bear cases.
      9. Price Target: 12-month forecast.
  
  expected_output: >
    A 600-word investment report with clear sections, key insights.
  
  
